name: superhuman
favicon: null
layout_spectrum: 0.1912096096202731
typography_spectrum: 0.6605061520822346
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7223505084402859
  lightness: 0.8964654081501067
  saturation: 0.26177447475492954
  rhythmicContrast: 0.8610440774355084
purpose: []
